name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v3.1.1, v3.2.0, etc.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v3.1.1)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PATD }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          release_name: Dorker ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
          body: |
            Release notes for Dorker ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}.
            - See commits for detailed changes.
          draft: false
          prerelease: false